language: node_js
sudo: false

cache:
  directories:
    - node_modules

env:
  matrix:
  - NODE_VER=4 FULL_VALIDATE=false
  - NODE_VER=6 FULL_VALIDATE=true alias danger=./node_modules/danger/distribution/danger
  - NODE_VER=7 FULL_VALIDATE=false
matrix:
  fast_finish: true

before_install:
  - nvm install $NODE_VER
  - npm install -g npm@4 && node -v && npm -v
  - if [ "$FULL_VALIDATE" == "true" ] && [ -n "DANGER_GITHUB_API_TOKEN" ]; then npm install danger && danger; fi

install:
  - npm install
  - if [ "$FULL_VALIDATE" == "true" ]; then npm run lint && npm run check_circular_dependencies; fi

script:
  - npm run build_spec && npm run test_mocha && node ./node_modules/markdown-doctest/bin/cmd.js

after_success:
  - if [ "$FULL_VALIDATE" == "true" ]; then npm run cover && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
  - if [ "$FULL_VALIDATE" == "true" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -n "$BROWSERSTACK_KEY" ]; then npm run build_spec_browser && browserstack-runner; fi
